### ISSUE TITLE
Create a new release for the 4.x branch with relax constraints

### ISSUE THREAD

**Issue by klaari** [digiaonline/lumen-contentful-sync#21]
I'm unable to install the 4.0.0 release with Lumen 6.x and nordsoftware/lumen-newrelic 2.0.2 
This is already in the master. The 4.x.x release is just missing.

**Comment by Jalle19** [comment]
What does Composer say?

**Comment by klaari** [comment]
Hi @Jalle19! 
Thanks for following up.

This is what the Composer says:

`composer require digiaonline/lumen-contentful-sync:^4.0
`

Problem 1
    - Root composer.json requires digiaonline/lumen-contentful-sync 4.0.0 -> satisfiable by digiaonline/lumen-contentful-sync[4.0.0].
    - digiaonline/lumen-contentful-sync 4.0.0 requires laravel/lumen-framework ^5.4 -> found laravel/lumen-framework[v5.4.0, ..., v5.8.13] but it conflicts with your root composer.json require (^6.0).
